---
- name: Download Zabbix-agent
  ansible.builtin.apt:
#    deb: "https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb"
    deb: "https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb"

- name: apt-get update
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix-agent  
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Copy Zabbix_agentd configuration
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes      

- name: Enable Zabbix-agent
  ansible.builtin.command:
    sudo systemctl enable zabbix-agent
    
- name: restart
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: yes
    state: restarted 
  with_items:
    - zabbix-agent 